//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HRMS_APP.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class hrms_appEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new hrms_appEntities object using the connection string found in the 'hrms_appEntities' section of the application configuration file.
        /// </summary>
        public hrms_appEntities() : base("name=hrms_appEntities", "hrms_appEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hrms_appEntities object.
        /// </summary>
        public hrms_appEntities(string connectionString) : base(connectionString, "hrms_appEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hrms_appEntities object.
        /// </summary>
        public hrms_appEntities(EntityConnection connection) : base(connection, "hrms_appEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppData> AppDatas
        {
            get
            {
                if ((_AppDatas == null))
                {
                    _AppDatas = base.CreateObjectSet<AppData>("AppDatas");
                }
                return _AppDatas;
            }
        }
        private ObjectSet<AppData> _AppDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<empCred> empCreds
        {
            get
            {
                if ((_empCreds == null))
                {
                    _empCreds = base.CreateObjectSet<empCred>("empCreds");
                }
                return _empCreds;
            }
        }
        private ObjectSet<empCred> _empCreds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoginCred> LoginCreds
        {
            get
            {
                if ((_LoginCreds == null))
                {
                    _LoginCreds = base.CreateObjectSet<LoginCred>("LoginCreds");
                }
                return _LoginCreds;
            }
        }
        private ObjectSet<LoginCred> _LoginCreds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RegistrationKey> RegistrationKeys
        {
            get
            {
                if ((_RegistrationKeys == null))
                {
                    _RegistrationKeys = base.CreateObjectSet<RegistrationKey>("RegistrationKeys");
                }
                return _RegistrationKeys;
            }
        }
        private ObjectSet<RegistrationKey> _RegistrationKeys;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppDatas(AppData appData)
        {
            base.AddObject("AppDatas", appData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the empCreds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToempCreds(empCred empCred)
        {
            base.AddObject("empCreds", empCred);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoginCreds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoginCreds(LoginCred loginCred)
        {
            base.AddObject("LoginCreds", loginCred);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RegistrationKeys EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegistrationKeys(RegistrationKey registrationKey)
        {
            base.AddObject("RegistrationKeys", registrationKey);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrms_appModel", Name="AppData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppData object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="empCode">Initial value of the EmpCode property.</param>
        /// <param name="appKey">Initial value of the AppKey property.</param>
        /// <param name="registered">Initial value of the Registered property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static AppData CreateAppData(global::System.Int32 id, global::System.Int32 empCode, global::System.String appKey, global::System.String registered, global::System.Double version, global::System.String status)
        {
            AppData appData = new AppData();
            appData.ID = id;
            appData.EmpCode = empCode;
            appData.AppKey = appKey;
            appData.Registered = registered;
            appData.Version = version;
            appData.Status = status;
            return appData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpCode
        {
            get
            {
                return _EmpCode;
            }
            set
            {
                OnEmpCodeChanging(value);
                ReportPropertyChanging("EmpCode");
                _EmpCode = StructuralObject.SetValidValue(value, "EmpCode");
                ReportPropertyChanged("EmpCode");
                OnEmpCodeChanged();
            }
        }
        private global::System.Int32 _EmpCode;
        partial void OnEmpCodeChanging(global::System.Int32 value);
        partial void OnEmpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AppKey
        {
            get
            {
                return _AppKey;
            }
            set
            {
                OnAppKeyChanging(value);
                ReportPropertyChanging("AppKey");
                _AppKey = StructuralObject.SetValidValue(value, false, "AppKey");
                ReportPropertyChanged("AppKey");
                OnAppKeyChanged();
            }
        }
        private global::System.String _AppKey;
        partial void OnAppKeyChanging(global::System.String value);
        partial void OnAppKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Registered
        {
            get
            {
                return _Registered;
            }
            set
            {
                OnRegisteredChanging(value);
                ReportPropertyChanging("Registered");
                _Registered = StructuralObject.SetValidValue(value, false, "Registered");
                ReportPropertyChanged("Registered");
                OnRegisteredChanged();
            }
        }
        private global::System.String _Registered;
        partial void OnRegisteredChanging(global::System.String value);
        partial void OnRegisteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, "Version");
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.Double _Version;
        partial void OnVersionChanging(global::System.Double value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrms_appModel", Name="empCred")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empCred : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new empCred object.
        /// </summary>
        /// <param name="empCode">Initial value of the EmpCode property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modifiedOn">Initial value of the ModifiedOn property.</param>
        /// <param name="isactive">Initial value of the isactive property.</param>
        /// <param name="loginattempts">Initial value of the loginattempts property.</param>
        public static empCred CreateempCred(global::System.Int32 empCode, global::System.String password, global::System.DateTime createdOn, global::System.DateTime modifiedOn, global::System.String isactive, global::System.Byte loginattempts)
        {
            empCred empCred = new empCred();
            empCred.EmpCode = empCode;
            empCred.Password = password;
            empCred.CreatedOn = createdOn;
            empCred.ModifiedOn = modifiedOn;
            empCred.isactive = isactive;
            empCred.loginattempts = loginattempts;
            return empCred;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpCode
        {
            get
            {
                return _EmpCode;
            }
            set
            {
                if (_EmpCode != value)
                {
                    OnEmpCodeChanging(value);
                    ReportPropertyChanging("EmpCode");
                    _EmpCode = StructuralObject.SetValidValue(value, "EmpCode");
                    ReportPropertyChanged("EmpCode");
                    OnEmpCodeChanged();
                }
            }
        }
        private global::System.Int32 _EmpCode;
        partial void OnEmpCodeChanging(global::System.Int32 value);
        partial void OnEmpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Salt
        {
            get
            {
                return _Salt;
            }
            set
            {
                OnSaltChanging(value);
                ReportPropertyChanging("Salt");
                _Salt = StructuralObject.SetValidValue(value, true, "Salt");
                ReportPropertyChanged("Salt");
                OnSaltChanged();
            }
        }
        private global::System.String _Salt;
        partial void OnSaltChanging(global::System.String value);
        partial void OnSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Algo
        {
            get
            {
                return _Algo;
            }
            set
            {
                OnAlgoChanging(value);
                ReportPropertyChanging("Algo");
                _Algo = StructuralObject.SetValidValue(value, "Algo");
                ReportPropertyChanged("Algo");
                OnAlgoChanged();
            }
        }
        private Nullable<global::System.Int32> _Algo;
        partial void OnAlgoChanging(Nullable<global::System.Int32> value);
        partial void OnAlgoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value, "CreatedOn");
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value, "ModifiedOn");
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private global::System.DateTime _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.DateTime value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String isactive
        {
            get
            {
                return _isactive;
            }
            set
            {
                OnisactiveChanging(value);
                ReportPropertyChanging("isactive");
                _isactive = StructuralObject.SetValidValue(value, false, "isactive");
                ReportPropertyChanged("isactive");
                OnisactiveChanged();
            }
        }
        private global::System.String _isactive;
        partial void OnisactiveChanging(global::System.String value);
        partial void OnisactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte loginattempts
        {
            get
            {
                return _loginattempts;
            }
            set
            {
                OnloginattemptsChanging(value);
                ReportPropertyChanging("loginattempts");
                _loginattempts = StructuralObject.SetValidValue(value, "loginattempts");
                ReportPropertyChanged("loginattempts");
                OnloginattemptsChanged();
            }
        }
        private global::System.Byte _loginattempts;
        partial void OnloginattemptsChanging(global::System.Byte value);
        partial void OnloginattemptsChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrms_appModel", Name="LoginCred")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoginCred : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoginCred object.
        /// </summary>
        /// <param name="empCode">Initial value of the EmpCode property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modifiedOn">Initial value of the ModifiedOn property.</param>
        /// <param name="isactive">Initial value of the isactive property.</param>
        /// <param name="loginattempts">Initial value of the loginattempts property.</param>
        public static LoginCred CreateLoginCred(global::System.Int32 empCode, global::System.String password, global::System.DateTime createdOn, global::System.DateTime modifiedOn, global::System.String isactive, global::System.Byte loginattempts)
        {
            LoginCred loginCred = new LoginCred();
            loginCred.EmpCode = empCode;
            loginCred.Password = password;
            loginCred.CreatedOn = createdOn;
            loginCred.ModifiedOn = modifiedOn;
            loginCred.isactive = isactive;
            loginCred.loginattempts = loginattempts;
            return loginCred;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpCode
        {
            get
            {
                return _EmpCode;
            }
            set
            {
                if (_EmpCode != value)
                {
                    OnEmpCodeChanging(value);
                    ReportPropertyChanging("EmpCode");
                    _EmpCode = StructuralObject.SetValidValue(value, "EmpCode");
                    ReportPropertyChanged("EmpCode");
                    OnEmpCodeChanged();
                }
            }
        }
        private global::System.Int32 _EmpCode;
        partial void OnEmpCodeChanging(global::System.Int32 value);
        partial void OnEmpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Salt
        {
            get
            {
                return _Salt;
            }
            set
            {
                OnSaltChanging(value);
                ReportPropertyChanging("Salt");
                _Salt = StructuralObject.SetValidValue(value, true, "Salt");
                ReportPropertyChanged("Salt");
                OnSaltChanged();
            }
        }
        private global::System.String _Salt;
        partial void OnSaltChanging(global::System.String value);
        partial void OnSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Algo
        {
            get
            {
                return _Algo;
            }
            set
            {
                OnAlgoChanging(value);
                ReportPropertyChanging("Algo");
                _Algo = StructuralObject.SetValidValue(value, "Algo");
                ReportPropertyChanged("Algo");
                OnAlgoChanged();
            }
        }
        private Nullable<global::System.Int32> _Algo;
        partial void OnAlgoChanging(Nullable<global::System.Int32> value);
        partial void OnAlgoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value, "CreatedOn");
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value, "ModifiedOn");
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private global::System.DateTime _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.DateTime value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String isactive
        {
            get
            {
                return _isactive;
            }
            set
            {
                OnisactiveChanging(value);
                ReportPropertyChanging("isactive");
                _isactive = StructuralObject.SetValidValue(value, false, "isactive");
                ReportPropertyChanged("isactive");
                OnisactiveChanged();
            }
        }
        private global::System.String _isactive;
        partial void OnisactiveChanging(global::System.String value);
        partial void OnisactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte loginattempts
        {
            get
            {
                return _loginattempts;
            }
            set
            {
                OnloginattemptsChanging(value);
                ReportPropertyChanging("loginattempts");
                _loginattempts = StructuralObject.SetValidValue(value, "loginattempts");
                ReportPropertyChanged("loginattempts");
                OnloginattemptsChanged();
            }
        }
        private global::System.Byte _loginattempts;
        partial void OnloginattemptsChanging(global::System.Byte value);
        partial void OnloginattemptsChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrms_appModel", Name="RegistrationKey")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegistrationKey : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RegistrationKey object.
        /// </summary>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="registrationKey1">Initial value of the RegistrationKey1 property.</param>
        public static RegistrationKey CreateRegistrationKey(global::System.String userid, global::System.String registrationKey1)
        {
            RegistrationKey registrationKey = new RegistrationKey();
            registrationKey.userid = userid;
            registrationKey.RegistrationKey1 = registrationKey1;
            return registrationKey;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value, false, "userid");
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.String _userid;
        partial void OnuseridChanging(global::System.String value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RegistrationKey1
        {
            get
            {
                return _RegistrationKey1;
            }
            set
            {
                if (_RegistrationKey1 != value)
                {
                    OnRegistrationKey1Changing(value);
                    ReportPropertyChanging("RegistrationKey1");
                    _RegistrationKey1 = StructuralObject.SetValidValue(value, false, "RegistrationKey1");
                    ReportPropertyChanged("RegistrationKey1");
                    OnRegistrationKey1Changed();
                }
            }
        }
        private global::System.String _RegistrationKey1;
        partial void OnRegistrationKey1Changing(global::System.String value);
        partial void OnRegistrationKey1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value, "CreatedAt");
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedAt;
        partial void OnCreatedAtChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrms_appModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrms_appModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="empCode">Initial value of the EmpCode property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="designation">Initial value of the Designation property.</param>
        /// <param name="grade">Initial value of the Grade property.</param>
        /// <param name="cell">Initial value of the Cell property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="modifiedOn">Initial value of the ModifiedOn property.</param>
        /// <param name="isenabled">Initial value of the isenabled property.</param>
        /// <param name="region">Initial value of the Region property.</param>
        public static User CreateUser(global::System.Int32 empCode, global::System.String name, global::System.String email, global::System.String designation, global::System.String grade, global::System.String cell, global::System.String status, global::System.DateTime createdOn, global::System.DateTime modifiedOn, global::System.String isenabled, global::System.String region)
        {
            User user = new User();
            user.EmpCode = empCode;
            user.Name = name;
            user.Email = email;
            user.Designation = designation;
            user.Grade = grade;
            user.Cell = cell;
            user.Status = status;
            user.CreatedOn = createdOn;
            user.ModifiedOn = modifiedOn;
            user.isenabled = isenabled;
            user.Region = region;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpCode
        {
            get
            {
                return _EmpCode;
            }
            set
            {
                if (_EmpCode != value)
                {
                    OnEmpCodeChanging(value);
                    ReportPropertyChanging("EmpCode");
                    _EmpCode = StructuralObject.SetValidValue(value, "EmpCode");
                    ReportPropertyChanged("EmpCode");
                    OnEmpCodeChanged();
                }
            }
        }
        private global::System.Int32 _EmpCode;
        partial void OnEmpCodeChanging(global::System.Int32 value);
        partial void OnEmpCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, false, "Designation");
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value, false, "Grade");
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private global::System.String _Grade;
        partial void OnGradeChanging(global::System.String value);
        partial void OnGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cell
        {
            get
            {
                return _Cell;
            }
            set
            {
                OnCellChanging(value);
                ReportPropertyChanging("Cell");
                _Cell = StructuralObject.SetValidValue(value, false, "Cell");
                ReportPropertyChanged("Cell");
                OnCellChanged();
            }
        }
        private global::System.String _Cell;
        partial void OnCellChanging(global::System.String value);
        partial void OnCellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Verifier
        {
            get
            {
                return _Verifier;
            }
            set
            {
                OnVerifierChanging(value);
                ReportPropertyChanging("Verifier");
                _Verifier = StructuralObject.SetValidValue(value, "Verifier");
                ReportPropertyChanged("Verifier");
                OnVerifierChanged();
            }
        }
        private Nullable<global::System.Int32> _Verifier;
        partial void OnVerifierChanging(Nullable<global::System.Int32> value);
        partial void OnVerifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Approver
        {
            get
            {
                return _Approver;
            }
            set
            {
                OnApproverChanging(value);
                ReportPropertyChanging("Approver");
                _Approver = StructuralObject.SetValidValue(value, "Approver");
                ReportPropertyChanged("Approver");
                OnApproverChanged();
            }
        }
        private Nullable<global::System.Int32> _Approver;
        partial void OnApproverChanging(Nullable<global::System.Int32> value);
        partial void OnApproverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AreaManager
        {
            get
            {
                return _AreaManager;
            }
            set
            {
                OnAreaManagerChanging(value);
                ReportPropertyChanging("AreaManager");
                _AreaManager = StructuralObject.SetValidValue(value, "AreaManager");
                ReportPropertyChanged("AreaManager");
                OnAreaManagerChanged();
            }
        }
        private Nullable<global::System.Int32> _AreaManager;
        partial void OnAreaManagerChanging(Nullable<global::System.Int32> value);
        partial void OnAreaManagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RegionalManager
        {
            get
            {
                return _RegionalManager;
            }
            set
            {
                OnRegionalManagerChanging(value);
                ReportPropertyChanging("RegionalManager");
                _RegionalManager = StructuralObject.SetValidValue(value, "RegionalManager");
                ReportPropertyChanged("RegionalManager");
                OnRegionalManagerChanged();
            }
        }
        private Nullable<global::System.Int32> _RegionalManager;
        partial void OnRegionalManagerChanging(Nullable<global::System.Int32> value);
        partial void OnRegionalManagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value, "CreatedOn");
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value, "ModifiedOn");
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private global::System.DateTime _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.DateTime value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String isenabled
        {
            get
            {
                return _isenabled;
            }
            set
            {
                OnisenabledChanging(value);
                ReportPropertyChanging("isenabled");
                _isenabled = StructuralObject.SetValidValue(value, false, "isenabled");
                ReportPropertyChanged("isenabled");
                OnisenabledChanged();
            }
        }
        private global::System.String _isenabled;
        partial void OnisenabledChanging(global::System.String value);
        partial void OnisenabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, false, "Region");
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OffList
        {
            get
            {
                return _OffList;
            }
            set
            {
                OnOffListChanging(value);
                ReportPropertyChanging("OffList");
                _OffList = StructuralObject.SetValidValue(value, true, "OffList");
                ReportPropertyChanged("OffList");
                OnOffListChanged();
            }
        }
        private global::System.String _OffList;
        partial void OnOffListChanging(global::System.String value);
        partial void OnOffListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Branch
        {
            get
            {
                return _Branch;
            }
            set
            {
                OnBranchChanging(value);
                ReportPropertyChanging("Branch");
                _Branch = StructuralObject.SetValidValue(value, true, "Branch");
                ReportPropertyChanged("Branch");
                OnBranchChanged();
            }
        }
        private global::System.String _Branch;
        partial void OnBranchChanging(global::System.String value);
        partial void OnBranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BO1
        {
            get
            {
                return _BO1;
            }
            set
            {
                OnBO1Changing(value);
                ReportPropertyChanging("BO1");
                _BO1 = StructuralObject.SetValidValue(value, "BO1");
                ReportPropertyChanged("BO1");
                OnBO1Changed();
            }
        }
        private Nullable<global::System.Int32> _BO1;
        partial void OnBO1Changing(Nullable<global::System.Int32> value);
        partial void OnBO1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BO2
        {
            get
            {
                return _BO2;
            }
            set
            {
                OnBO2Changing(value);
                ReportPropertyChanging("BO2");
                _BO2 = StructuralObject.SetValidValue(value, "BO2");
                ReportPropertyChanged("BO2");
                OnBO2Changed();
            }
        }
        private Nullable<global::System.Int32> _BO2;
        partial void OnBO2Changing(Nullable<global::System.Int32> value);
        partial void OnBO2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BO3
        {
            get
            {
                return _BO3;
            }
            set
            {
                OnBO3Changing(value);
                ReportPropertyChanging("BO3");
                _BO3 = StructuralObject.SetValidValue(value, "BO3");
                ReportPropertyChanged("BO3");
                OnBO3Changed();
            }
        }
        private Nullable<global::System.Int32> _BO3;
        partial void OnBO3Changing(Nullable<global::System.Int32> value);
        partial void OnBO3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtensionNum
        {
            get
            {
                return _ExtensionNum;
            }
            set
            {
                OnExtensionNumChanging(value);
                ReportPropertyChanging("ExtensionNum");
                _ExtensionNum = StructuralObject.SetValidValue(value, true, "ExtensionNum");
                ReportPropertyChanged("ExtensionNum");
                OnExtensionNumChanged();
            }
        }
        private global::System.String _ExtensionNum;
        partial void OnExtensionNumChanging(global::System.String value);
        partial void OnExtensionNumChanged();

        #endregion

    }

    #endregion

}
